### ISSUE TITLE
Find out wich files and directories to make persistant

### ISSUE THREAD

**Issue by viper0131** [viper0131/check_mk#1]
**Files or locations to have persistant:**
-     the main configuration file (main.mk)
-     the final configuration file final.mk, if present
-     all files in your configuration subdirectory conf.d, if present
-     automatically inventorized checks (usually /var/lib/check_mk/autochecks)
-     current performance counters (usually /var/lib/check_mk/counters)
-     stored logfiles of logwatch (usually /var/lib/check_mk/logwatch)
-     cached files from the agents (usually /var/lib/check_mk/cache)

**Comment by gersilex** [comment]
Can we support you in any way? Looks like persisting the work dir `/omd` is not an option?

**Comment by mcgege** [comment]
@viper0131 Is this still an issue? One could map `/opt/omd` to the local filesystem with `-v` if the files should persist ... in my installation I'm mapping in a backup directory and use the builtin backup feature of check_mk.

Maybe we should add a section to the documentation?

**Comment by viper0131** [comment]
Sounds great Michael

Verstuurd vanaf mijn iPhone

**Comment by mcgege** [comment]
Solved by documentation update
