### ISSUE TITLE
Latest Tag not found

### ISSUE THREAD

**Issue by SportySeb** [viper0131/check_mk#11]
executing the documented command 
`docker pull nlmacamp/check_mk:1.4.0p10`
I get the messages
```
Pulling repository docker.io/nlmacamp/check_mk
Tag 1.4.0p10 not found in repository docker.io/nlmacamp/check_mk
```

**Comment by mcgege** [comment]
I‘ll look into this the next days ... meanwhile try `docker pull nlmacamp/check_mk:latest`

**Comment by mcgege** [comment]
@viper0131 It seems to me that you have statically defined which tags should be build on Docker Hub ... I think you have to setup the autobuild tags as described [here](https://docs.docker.com/docker-hub/builds/#create-an-automated-build)

**Comment by SportySeb** [comment]
I only followed the instructions given in https://hub.docker.com/r/nlmacamp/check_mk/

There is written

```
`Automated builds of the image are available on Dockerhub and is the recommended method of installation.

docker pull nlmacamp/check_mk:1.4.0p10

Alternatively you can build the image yourself.`

```
This does not indicate to me, that I as a user have todo anything more than executing
> docker pull nlmacamp/check_mk:1.4.0p10

does that documentation should get improved ?

**Comment by mcgege** [comment]
@SportySeb You have done everything right - the link between GitHub and Docker Hub is broken (and the repository owner @viper0131 must change the settings in Docker Hub).

I have just updated check_mk in this repo to 1.4.0p13 and updated the documentation (that you could also use the **latest** tag instead of the version number) ... should be available in Docker Hub within 24 hours.

**Comment by viper0131** [comment]
I’m away for a few days.  Will check the broken link when ‘m back

Verstuurd vanaf mijn iPhone

**Comment by viper0131** [comment]
changed buildconfig on dockerhub, also removed and added the 1.4.0p10 to trigger the build for an already existing tag as mentioned in https://success.docker.com/Cloud/Solve/Trigger_A_Build_For_An_Automated_Build_Tag
The build is queued, give it a few hours

**Comment by viper0131** [comment]
seems ok now:

$ docker pull nlmacamp/check_mk:1.4.0p10
1.4.0p10: Pulling from nlmacamp/check_mk
b8e0383d5f94: Pull complete
ecacb4c1c87b: Pull complete
175840c9231a: Pull complete
e9defa00ebdc: Pull complete
4d35d70c23cb: Pull complete
509a47064fd2: Pull complete
Digest: sha256:a5d7869b8ce4d69e216ae4aa1de548339f5436e0fa77d355890e4a71155d90a0
Status: Downloaded newer image for nlmacamp/check_mk:1.4.0p10

**Comment by mcgege** [comment]
@viper0131 v1.4.0 seems to work (the newest tag 1.4.0p13 is also visible) ... maybe you could also include the 1.2.8 branch (tag 1.2.8p25) in the autobuild?
