### ISSUE TITLE
omd: command not found

### ISSUE THREAD

**Issue by abal5** [viper0131/check_mk#18]
I get an error message when running this container, I have tried building it manually and also doing a docker pull.

Docker version being used is: 17.09.0-ce I've also tried 17.12.0-ce

I get this error below:

`/opt/bootstrap.sh: line 20: omd: command not found`

If the rpm package is installed is that sufficient enough to call on omd or could the ordering be wrong?

I have done a manual pull on my machine and that does not work, I originally had this running as a container using Rancher and it seemed to be working fine but no longer is the case.

**Comment by viper0131** [comment]
Hi Anmol,

Can you give some more details about how you start the container?

Machiel

**Comment by viper0131** [comment]
I pulled the latest image myself for testing. I run's fine with the following command:

`docker run -it --name check_mk --publish 80:5000 --rm nlmacamp/check_mk`

You can also try debugging by skipping the default entrypoint:

`docker run -it --name check_mk --publish 80:5000 --entrypoint=/bin/bash --rm nlmacamp/check_mk`

It will give you the bash command prompt.
try to enter 

`omd version`

this should show:
OMD - Open Monitoring Distribution Version 1.4.0p21.cre

**Comment by abal5** [comment]
These are the commands I am using to start the container:

`docker run -itd --name check_mk2018 \
           --publish 80:5000 \
           --restart always \
           --volume /home/ops/check-mk:/opt/omd \
           -e "MAILHUB=<172.16.2.202:9025>" \
           nlmacamp/check_mk`
