### ISSUE TITLE
Volume mapping suggested prevents startup

### ISSUE THREAD

**Issue by keithy** [viper0131/check_mk#19]
If you actually use this mapping as written then it overwrites the binary `omd` amongst other things.

> If your want to keep your configuration files + performance data persistent, you have to map the /opt/omd directory to the local filesystem like this:
> 
>   --volume <localdir>:/opt/omd

K.

**Comment by mcgege** [comment]
Thanks @keithy ... as I have no quick solution for this (do you have an idea?) I took it out of the README.

**Comment by keithy** [comment]
I just added --volume /Users/mydir/check_mk_home:/share
Just in case it might be useful
