### ISSUE TITLE
Missing PNP4NAGIOS

### ISSUE THREAD

**Issue by sweitzel** [viper0131/check_mk#42]
Thank you for providing a usable Docker version of check_mk (unfortunately the Dockerfile for the check_mk docker version by creator of check_mk is not public (or I couldnt find it).

The only obvious missing thing for me is the graphing. There are graph buttons by default after accessing the Docker based check_mk instance, however PNP4NAGIOS is not installed and thus the images wont load.

Can you implement PNP4NAGIOS support please?

**Comment by sweitzel** [comment]
I have an Apache HTTPD reverse proxy on my Docker Host with following proxy config:
could you give a hint how to change this to get PNP4NAGIOS working?
```
  # check_mk
  RewriteRule ^/omd/check_mk/(.*)$ /monitor/$1 [R=permanent,L]
  SetEnv force-proxy-request-1.0 1
  SetEnv proxy-nokeepalive 1

  ProxyPass        "/monitor/"     "http://localhost:5000/omd/check_mk/"
  ProxyPassReverse "/monitor/"     "http://localhost:5000/omd/check_mk/"
```

**Comment by mcgege** [comment]
Hmm ... my graph url looks like this:

```
http://<myhost>:81/mva/pnp4nagios/index.php/graph?host=Box&srv=_HOST_&theme=multisite&baseurl=../check_mk/
```

Maybe you have to include this somehow in your proxy rules?

**Comment by sweitzel** [comment]
Great, that solved it. I had to add actually to ProxyPass directives to make it work.
The PNP HTML pages where loaded from /pnp4nagios, not /omd/pnp4nagios.

Complete proxy config part now:
```
  RewriteEngine on
  # check_mk
  RewriteRule ^/omd/check_mk/(.*)$ /monitor/$1 [R=permanent,L]
  SetEnv force-proxy-request-1.0 1
  SetEnv proxy-nokeepalive 1

  ProxyPass        "/pnp4nagios"  "http://localhost:5000/omd/pnp4nagios"
  ProxyPassReverse "/pnp4nagios"  "http://localhost:5000/omd/pnp4nagios"
  ProxyPass        "/omd/pnp4nagios"  "http://localhost:5000/omd/pnp4nagios"
  ProxyPassReverse "/omd/pnp4nagios"  "http://localhost:5000/omd/pnp4nagios"
  ProxyPass        "/monitor/"     "http://localhost:5000/omd/check_mk/"
  ProxyPassReverse "/monitor/"     "http://localhost:5000/omd/check_mk/"
```
